spring:
  datasource:
    name: scDataSource
    url: jdbc:mysql://127.0.0.1:3306/sc_manage?scharacterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  config: classpath:config/logback.xml
  
server:
  port: 8090
  
system:
   enableSwagger: true    #是否启用swagger  
   file:
     path: /Users/xcj/git/sc-manage/tmp/
   
   
  